### ISSUE TITLE
poprawki

### ISSUE THREAD

**Issue by Dominika29** [Dominika29/projekt-psio#10]
dodano:
klasa bazowa Character,
uzyte w niej : unique_ptr i realizuje polimorfizm,
poprawione boundsy w quest II, ale nie udało się do końca tego usprawnić.
zmieniona koncepcja questu III, jednak coiny spawnują się czasami w bohaterze, do tego boundsy wszerz dalej są zbugowane.

**Comment by JOtworowski** [comment]
Poprawki jak widzę znajdują się na branchu dev, jednak tam widzę że jest nie wszystkie commity z maina są tam dograne. Proszę przygotujcie ostatecznie zmergowaną wersję i wtedy ją ocenię

**Comment by Dominika29** [comment]
chyba teraz wszystko jest juz na mainie

**Comment by JOtworowski** [comment]
Projekt znacznie usprawniony. Poprawiono zarówno pod względem graficznym jak i poprawności działania. Quest 3 działa poprawnie. Wykorzystanie unique_ptr znalazłem i widzę że zostało poprawnie zrealizowane.

Biorąc pod uwagę wszystkie ulepszenia mogę zgodzić się na podniesienie oceny do 90%.
