### ISSUE TITLE
Final Project

### ISSUE THREAD

**Issue by Dominika29** [Dominika29/projekt-psio#9]
## Final Project

gotowy projekt znajduje sie w branchu dev, w x64->release-? release.zip gra otwiera sie z .exe

**Comment by JOtworowski** [comment]
Projekt bardzo ładny pod kątem "artystycznym" niestety wydaje się w pewnym stopniu niedokończony. Pierwszy quest działa bez zarzutu, drugi początkowo również był ok jednak wydaje mi się że wykrywanie hitboxa bohatera nie działa poprawnie. Działania questu nr 3 nie potrafię zrozumieć po jakimś czasie wyświetla się po prostu informacja o porażce. Fajnym rozwiązaniem jest otwieranie questów w osobnych oknach. Dziedziczenie zostało zrealizowane częściowo, ponieważ znalazłem dziedziczenie jedynie po klasach z biblioteki sfml. Nie znalazłem również wykorzystania polimorfizmu i unique_ptr. Projekt odpala się z pliku .exe bez problemu. Repozytorium na githubie prowadzone jest poprawnie choć plik readme nie spełnia wymagań

Proponuje ocenę 77,5 %, ponieważ projekt jest bardzo ładny i świetnie animowany jednak brakuje w nim warstwy rozgrywki i po uruchomieniu questu nr 3 zaczyna działać w sposób nieprzewidywalny
